version: '3.8'

services:
    postgres: 
      container_name: postgres-contenedor
      image:  postgres:11
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=root
        - POSTGRES_USER=root
        - POSTGRES_DB=presentacionDB
        - POSTGRES_HOST=127.0.0.1
      volumes:
        - ./database-seed.sql:/docker-entrypoint-initdb.d/database-seed.sql

    pgadmin:
      container_name: pgadmin_postgres_contenedor
      image: dpage/pgadmin4
      restart: always
      environment:
        PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
        PGADMIN_DEFAULT_PASSWORD: "admin"
      ports:
        - "8080:80"
      depends_on:
        - postgres

    app:
        container_name: node_contenedor
        image: node-docker
        ports:
          - 13000:3000
